<%@ Page Language="C#" MasterPageFile="~/App_Utility/MasterPage/MasterBule.master" ValidateRequest="false" AutoEventWireup="true" CodeBehind="FinatialCompany.aspx.cs" Inherits="FrmPresentation.App_Pages.Finance.FinatialCompany" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"  >
    <style type="text/css">
        .Btn
        {
            BACKGROUND-REPEAT: no-repeat;	
	        BACKGROUND-COLOR: transparent;
	         BORDER-RIGHT: #346fa4 2px solid; 
	        BORDER-TOP: lightsteelblue 2px solid; 
	        BORDER-LEFT: lightsteelblue 2px solid; 
	        BORDER-BOTTOM: #346fa4 2px solid;  
	        WIDTH: 70px;
	        HEIGHT: 32px
        }
        
    </style>
    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <asp:ScriptManager ID="ScriptManager1" runat="server">
     </asp:ScriptManager>
       
     <script language="javascript" type="text/javascript">
        window.name = "FinatialCompany"
        aspnetForm.target = window.name;
         var MasterObj = "ctl00_ContentPlaceHolder1_";
         Sys.WebForms.PageRequestManager.getInstance().add_endRequest(EndRequestHandler);
         function EndRequestHandler(sender, args) {
             if ($get(MasterObj + "txtAlert").value != "") {
                 alert($get(MasterObj + "txtAlert").value);
                 $get(MasterObj + "txtAlert").value = "";
                 if ($get(MasterObj + "txtSaveStatus").value == "1")
                      window.close();
             }
         }
     </script>   
   
       <table style="height:100%;width:100%">
           <tr style="height:75%; position:fixed">
               <td  >
                   <table style="height:100%;width:100%">
                       <tr align="right">
                           <td align="right">
                              <asp:TreeView ID="tvControl" runat="server" 
                                 AutoGenerateDataBindings="False" dir="rtl" 
                                 SelectedNodeStyle-ForeColor="Red"
                                LineImagesFolder="../../App_Utility/Images/TreeLineImages"  ShowLines="True" >
                              </asp:TreeView>
                               &nbsp;</td>
                       </tr>
                   </table>
               </td>
           </tr>
           <tr valign="bottom" style="height:25%;position:fixed">
               <td valign="bottom">
                   <table style="height:100%;width:100%">
                       <tr >
                           <td align="left">
                            <img alt="ذخيره" class="Btn" src="../../App_Utility/Images/Icons/Save.gif"  
                                   onclick="OnClickBtnSave()" id="SaveBtn" />
                               &nbsp;</td>
                           <td>
                            <img alt="انصراف" class="Btn" 
                                   src="../../App_Utility/Images/Icons/Cancel.gif" onclick="OnClickBtnClose()" 
                                   id="CancleBtn" />
                               &nbsp;</td>
                       </tr>
                   </table>
               </td>
           </tr>
     </table>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
         <ContentTemplate>
             <asp:HiddenField ID="txtAlert" runat="server" />
              <asp:HiddenField ID="txtSaveStatus" runat="server" />
         </ContentTemplate>
          <Triggers>
              <asp:AsyncPostBackTrigger ControlID="BtnSubmit" EventName="click" />
         </Triggers>
   </asp:UpdatePanel>
   
   <div style="display:none">
       <asp:Button ID="BtnSubmit" runat="server" Text="BtnSubmit" 
           onclick="BtnSubmit_Click" />
       <input type="text" runat="server" id="txtSubmit" />
       <input type="text" runat="server" id="txtFinanceID" />
      
   </div>
   
<script language="javascript" type="text/javascript">

    var MasterObj = "ctl00_ContentPlaceHolder1_";
    var nodeText;
    function OnClickBtnSave() {
      
        $get(MasterObj + "txtSubmit").value = "Save";
        $get(MasterObj + "BtnSubmit").click();
        returnValue = nodeText;
      
    }
    function OnClickBtnClose() {
        window.close();
        }
    
    function OnTreeClick(evt) {
        var src = window.event != window.undefined ? window.event.srcElement : evt.target;
        var nodeClick = src.tagName.toLowerCase() == "a";
        var index;
        var len;
        if (nodeClick) {
           
            nodeText = src.innerText || src.innerHTML;
            var nodeValue = GetNodeValue(src);
           // alert("Text: " + nodeText + "," + "Value: " + nodeValue);
            index = nodeValue.indexOf('#', 0);
            len = nodeValue.length;
            if (nodeValue.substr(0, 1) != "4")
                alert("لطفا روی سال مالی مورد نظر کلیک کنید");
            else {
                nodeValue = nodeValue.substr(index + 1, len - index);
                $get(MasterObj + "txtFinanceID").value = nodeValue;
            }
            
        }
        return false; //comment this if you want postback on node click
    }
    function GetNodeValue(node) {
        var nodeValue = "";
        var nodePath = node.href.substring(node.href.indexOf(",") + 2, node.href.length - 2);
        var nodeValues = nodePath.split("\\");
        if (nodeValues.length > 1)
            nodeValue = nodeValues[nodeValues.length - 1];
        else
            nodeValue = nodeValues[0].substr(1);

        return nodeValue;
    }

    

</script>   
</asp:Content>
