<%@ Page Language="C#" MasterPageFile="~/App_Utility/MasterPage/MasterBule.master"
    AutoEventWireup="true" CodeBehind="DefaultPage.aspx.cs" Inherits="FrmPresentation.App_Pages.Setting.DefaultPage"
    Title="Untitled Page" %>

<%@ Register Src="../../App_Utility/ToolBar/ToolBar.ascx" TagName="ToolBar" TagPrefix="uc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table>
        <tr>
            <td>
                <uc1:ToolBar ID="OToolBar" PageName="DefaultPage.aspx" PageID="1134" runat="server" />

                <script language="javascript" type="text/javascript" src="../../App_Utility/Scripts/General.js"></script>

                <asp:ScriptManager ID="ScriptManager1" runat="server" LoadScriptsBeforeUI="false"
                    ScriptMode="Release">
                </asp:ScriptManager>

                <script type="text/javascript" language="javascript">
                    Sys.WebForms.PageRequestManager.getInstance().add_beginRequest(BeginRequestHandler);
                    Sys.WebForms.PageRequestManager.getInstance().add_endRequest(EndRequestHandler);
                    function BeginRequestHandler(sender, args) {
                        //if (args.get_postBackElement().id == "ctl00_ContentPlaceHolder1_BtnSubmit")
                        
                    }
                    function EndRequestHandler(sender, args) {
                       
                        
                        if ($get(MasterObj + "txtAlert").value != "")
                            SetMsg($get(MasterObj + "txtAlert").value);
                        $get(MasterObj + "txtAlert").value = ""
                    }
                </script>

            </td>
        </tr>
        <tr valign="middle">
            <td align="right" width="500px">
                زیر سیستم:&nbsp;&nbsp;
                <asp:DropDownList onkeypress="return KeySort(this,false)" onchange="onchangeCmbSubSystem()"
                    ID="CmbSubSystem" runat="server" Width="120px">
                </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td>
                <div class="cssDiv" style="height: 450px; width: 500px;">
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
                        <ContentTemplate>
                            <asp:TreeView ID="tvControl" runat="server" LineImagesFolder="../../App_Utility/Images/TreeLineImages"
                                ShowLines="True" AutoGenerateDataBindings="False" OnSelectedNodeChanged="tvControl_SelectedNodeChanged">
                            </asp:TreeView>
                            <asp:HiddenField ID="txtSubsysID" runat="server" />
                            <asp:HiddenField ID="txtMenuItem" runat="server" />
                            <asp:HiddenField ID="txtAlert" runat="server" />
                            <asp:HiddenField ID="txtAcCode" runat="server" />
                        </ContentTemplate>
                        <Triggers>
                            <asp:AsyncPostBackTrigger ControlID="BtnSubmit" EventName="click" />
                            <asp:AsyncPostBackTrigger ControlID="tvControl" EventName="SelectedNodeChanged" />
                        </Triggers>
                    </asp:UpdatePanel>
                </div>
            </td>
        </tr>
        <tr>
            <td style="display: none">
                <input type="text" id="txtSubmit" name="txtSubmit" runat="server" />
                <asp:Button ID="BtnSubmit" runat="server" Text="BtnSubmit" OnClick="BtnSubmit_Click" />
            </td>
        </tr>
    </table>

    <script type="text/javascript" language="javascript">
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Declaration!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        var MasterObj = "ctl00_ContentPlaceHolder1_";
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        function onchangeCmbSubSystem() {
            document.getElementById(MasterObj + "txtSubsysID").value = document.getElementById(MasterObj + "CmbSubSystem").value
            $get(MasterObj + "txtSubmit").value = "changeSubSystem";
            document.getElementById(MasterObj + "BtnSubmit").click();
        }
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        function OnClickBtnSave() {
            document.getElementById(MasterObj + "txtAcCode").value = GetAccessCode(window.event.srcElement) 
            if (($get(MasterObj + "txtMenuItem").value == "") || ($get(MasterObj + "txtMenuItem").value == "0")) {
                alert("هیچ صفحه ای به عنوان صفحه پیش فرض انتخاب نشده")
            }
            else {
                $get(MasterObj + "txtSubmit").value = "Save";
                document.getElementById(MasterObj + "BtnSubmit").click();
            }
        }
        //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    </script>

</asp:Content>
