<%@ Page Title="" Language="C#" MasterPageFile="~/App_Utility/MasterPage/MasterBule.master"
    AutoEventWireup="true" CodeBehind="OrganChart.aspx.cs" Inherits="FrmPresentation.App_Pages.OrganizationChart.OrganChart" %>

<%@ Register TagPrefix="cc1" Namespace="KasraDll" Assembly="KasraDll" %>
<%@ Register Assembly="KasraComponent" Namespace="KasraComponent.Classes" TagPrefix="cc2" %>
<%@ Register Src="~/App_Utility/ComboBox/ComboBox.ascx" TagName="ComboBox" TagPrefix="uc2" %>
<%@ Register Src="~/App_Utility/ToolBar/ToolBar.ascx" TagName="ToolBar" TagPrefix="uc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <table width="100%">
        <tr>
            <td>
                <fieldset dir="rtl" class="fieldsetStyle">
                    <legend class="legendStyle">پارامترهای جستجو</legend>
                    <table>
                        <tr>
                            <td>
                                واحد سازمانی :
                            </td>
                            <td >
                                <asp:DropDownList ID="CmbDepartment" runat="server" Width="150" class="TxtControls">
                                </asp:DropDownList>
                            </td>
                            <td style="width: 100px">
                            </td>
                            <td>
                                شماره پرسنلی :
                            </td>
                            <td id="test">
                                <uc2:ComboBox ID="cmbPerson" runat="server" />
                            </td>
                        </tr>
                    </table>
                </fieldset> 
            </td>
        </tr>
        <tr>
            <td>
                <uc1:ToolBar ID="OToolBar" runat="server" />
            </td>
        </tr>
        <tr>
            <td>
                <table>
                    <tr valign="top">
                        <td>
                            <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
                                <ContentTemplate>                                
                                    <div id="DivTree" align="right" dir="rtl" style="width: 250px; height: 400px; overflow: auto"
                                        style="border: 1px solid #66CCFF; width: 200px; height: 200px; scrollbar-hightlight-color: white;
                                        scrollbar-arrow-color: black; scrollbar-base-color: #B1D3FF;" >
                                        <asp:TreeView ID="TreeDepatment" ShowExpandCollapse="true" runat="server" Height="98%"
                                            Width="245px" ForeColor="Black" HoverNodeStyle-ForeColor="#9932CC" AutoGenerateDataBindings="true"
                                            RootNodeStyle-ImageUrl="~/App_Utility/Images/TreeViewImage/folders.gif" NodeStyle-ImageUrl="~/App_Utility/Images/TreeViewImage/folder.gif"
                                            OnSelectedNodeChanged="TreeDepatment_SelectedNodeChanged" ShowLines="True"
                                            SelectedNodeStyle-BorderWidth="1px" dir="rtl" align="right">
                                        </asp:TreeView>
                                        <input type="text" id="txtTemp" name="txtPersonCode" style="display:none" runat="server" />         

                                    </div>
                                </ContentTemplate>
                                <Triggers>                                   
                                    <asp:AsyncPostBackTrigger ControlID="BtnSubmittree" EventName="click" />
                                    <asp:AsyncPostBackTrigger ControlID="BtnSubmitFilter" EventName="click" />
                                </Triggers>
                            </asp:UpdatePanel>
                        </td>
                        <td>
                            <asp:UpdatePanel ID="UpdatePanel2" runat="server" UpdateMode="Conditional">
                                <ContentTemplate>
                                    <div id="GridViewCountainer" style="height: 400px; width: 730px; overflow: auto"
                                        align="right">
                                        <cc2:KasraGrid ID="GrdDepartmentPerson" runat="server" OnRowDataBound="Grid_RowDataBound">
                                        </cc2:KasraGrid>
                                    </div>
                                    <asp:HiddenField ID="txtDepartmentID" runat="server" />
                                    <asp:HiddenField ID="txtMaxNumber" runat="server" />
                                    <asp:HiddenField ID="txtAlert" runat="server" />
                                    <asp:HiddenField ID="txtValidate" runat="server" />
                                    <asp:HiddenField ID="txtNodeValue" runat="server" />
                                </ContentTemplate>
                                <Triggers>
                                    <asp:AsyncPostBackTrigger ControlID="TreeDepatment" EventName="SelectedNodeChanged" />
                                    <asp:AsyncPostBackTrigger ControlID="BtnSubmit" EventName="click" />
                                    <asp:AsyncPostBackTrigger ControlID="BtnSubmitFilter" EventName="click" />
                                </Triggers>
                            </asp:UpdatePanel>
                        </td>
                         <td>
                            <asp:UpdatePanel ID="UpdatePanel3" runat="server" UpdateMode="Conditional">
                                <ContentTemplate>
                                    <asp:HiddenField ID="txtPersonName" runat="server" />
                                      <asp:HiddenField ID="txtxmlperson" runat="server" />
                                </ContentTemplate>
                                <Triggers>
                                    <asp:AsyncPostBackTrigger ControlID="BtnSubmitPerson" EventName="click" />
                                </Triggers>
                            </asp:UpdatePanel>
                         </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <div style="display: none">
        <cc1:MySecurity ID="OnLineUser" runat="server">
        </cc1:MySecurity>
        <asp:Button ID="BtnSubmit" runat="server" Text="Button" OnClick="BtnSubmit_Click" />
         <asp:Button ID="BtnSubmittree" runat="server" Text="Button" OnClick="BtnSubmittree_Click" />
         <asp:Button ID="BtnSubmitFilter" runat="server" Text="Button" OnClick="BtnSubmit_Click" />
        <asp:Button ID="BtnSubmitPerson" runat="server" Text="Button" OnClick="BtnSubmit_Click" />
        <input type="text" id="txtSubmit" name="txtSubmit" runat="server" />
        <input type="text" id="txtOnLineUser" name="txtOnLineUser" runat="server" />
        <input type="text" id="txtSessionID" name="txtSessionID" runat="server" />
        <input type="text" id="txtGetCompanyFinatialPeriodID" name="txtGetCompanyFinatialPeriodID"
            runat="server" />
        <%--<input type="text" id="txtDepartmentID" name="txtDepartmentID" runat="server" />--%>
        <input type="text" id="txtCmbCodePName" name="txtCmbCodePName" runat="server" />
        <input type="text" id="txtCmbCodePCode" name="txtCmbCodePCode" runat="server" />
        <input type="text" id="txtAlertPerson" name="txtAlertPerson" runat="server" />
        <input type="text" id="txtCount" name="txtCount" runat="server" />
        <input type="text" id="txtXmlSave" name="txtXmlSave" runat="server" /> 
        <input type="text" id="txtPersonCode" name="txtPersonCode" runat="server" /> 
        <input type="text" id="txtXmlStr" name="txtXmlStr" runat="server" />  
        <input type="text" id="txtDeleteFlag" name="txtDeleteFlag" runat="server" />
    </div>
      <script src="../../App_Utility/Scripts/jquery-1.4.1.min.js" type="text/javascript"></script>
    <script type="text/javascript" language="javascript">
        //================================================================================================
        var LastSelectedRow = null;
        var LastSelectedRowClass = "";
        document.dir = "rtl"
        document.body.style.overflowY = "hidden"
        var MasterObj = "ctl00_ContentPlaceHolder1_";
        var str =""
      
        //=================================For Click in RadioButton========================================
        $(document).ready(function () {           
            var DepartmentID;
            var RowIndex;

            $(':input[type="checkbox"]').live("click", function () {
                var Flag = this.checked; //For onclick again
                $($(':input[type="checkbox"]') + '[Checked=true]').each(function () {
                    this.checked = false;
                    DepartmentID=this.parentElement.parentElement.parentElement
                });
                this.checked = Flag;


                MakeXmlGrid(this, "CheckBox")
            });

        });
        //===========================================Ajax====================================================
        Sys.WebForms.PageRequestManager.getInstance().add_beginRequest(BeginRequestHandler)
        Sys.WebForms.PageRequestManager.getInstance().add_endRequest(EndRequestHandler)
        //===================================================================================================
        function BeginRequestHandler(sender, args) {
            if ($get(MasterObj + "txtSubmit").value == "BlurPerson")
                document.getElementById("ctl00_ProgressState").value = 1;
            document.getElementById('OToolBar_ProgressBar').style.visibility = "visible";
            //$get(MasterObj + "txtAlert").value = "";
        }
        //====================================================================================================
        function EndRequestHandler(sender, args) {
            document.getElementById('OToolBar_ProgressBar').style.visibility = "hidden";
            var StrSubmit = $get(MasterObj + "txtSubmit").value
            
            if (StrSubmit == "BlurPerson") {
                //alert(document.getElementById(MasterObj + "txtxmlperson").value)
                if ($get(MasterObj + "txtAlert").value != "")
                    SetMsg($get(MasterObj + "txtAlert").value)
                else {
                    var OGrdDepartmentPerson = document.getElementById(MasterObj + "GrdDepartmentPerson");
                    OGrdDepartmentPerson.rows(RowIndex).cells(5).innerHTML = $get(MasterObj + "txtPersonName").value
                }
            }
            if (StrSubmit == "Filter") {
//                alert($get(MasterObj + "txtTemp").value);
                //                $get("DivTree").scrollTop = $get(MasterObj + "txtTemp").value;
                ScrollToSelectedNode();
            }
            //===========
            if (StrSubmit == "Modify") {
                if ($get(MasterObj + "txtAlert").value != "") {
                    if ($get(MasterObj + "txtValidate").value == "1") {
                        SaveFlag = "1";
                        window.returnValue = SaveFlag;
                        SetMsg($get(MasterObj + "txtAlert").value)
                    }
                    else
                        alert($get(MasterObj + "txtAlert").value);
                }
            }
            //================
            if (StrSubmit == "Delete") {
                if ($get(MasterObj + "txtAlert").value != "") {
                    if ($get(MasterObj + "txtValidate").value == "1") {
                        SetMsg($get(MasterObj + "txtAlert").value)
                    }
                    else
                        alert($get(MasterObj + "txtAlert").value);
                }
            }
            //================
            $get(MasterObj + "txtAlert").value = ""
            LoadXMLGrid();
            str = ""
            LastSelectedRow = null
        }
        //==============================for new row=========================================
        function OnClickBtnNewRowPerson(obj) {
            var RowIndex = obj.parentElement.parentElement.rowIndex;
            var OGrdDepartmentPerson = document.getElementById(MasterObj + "GrdDepartmentPerson");
            var oRow = OGrdDepartmentPerson.insertRow();
            oRow.className = "CssItemStyle";
            oRow.setAttribute('Flag', 0);
            //oRow.setAttribute('PersonID', 0);
            oRow.attachEvent('onclick', OnClickGrd)


            var oCell0 = oRow.insertCell();
            oCell0.innerHTML = OGrdDepartmentPerson.rows(RowIndex).cells(0).innerHTML
            oCell0.firstChild.checked = false;

            var oCell1 = oRow.insertCell();
            oCell1.innerHTML = OGrdDepartmentPerson.rows(RowIndex).cells(1).innerHTML
            oCell1.firstChild.value = 0

            var oCell2 = oRow.insertCell();
            oCell2.innerHTML = OGrdDepartmentPerson.rows(RowIndex).cells(2).innerHTML;
            oCell2.innerText = ""

            var oCell3 = oRow.insertCell();
            oCell3.innerHTML = OGrdDepartmentPerson.rows(RowIndex).cells(3).innerHTML
            oCell3.firstChild.value = "";

            var oCell4 = oRow.insertCell();
            oCell4.innerHTML = OGrdDepartmentPerson.rows(RowIndex).cells(4).innerHTML
            oCell4.firstChild.value = ""

            var oCell5 = oRow.insertCell();
            oCell5.innerHTML = OGrdDepartmentPerson.rows(RowIndex).cells(5).innerHTML
            oCell5.innerText = ""

            var oCell6 = oRow.insertCell();
            oCell6.innerHTML = OGrdDepartmentPerson.rows(RowIndex).cells(6).innerHTML

        }
        //=============================For txtPerson... in Grid=======================
        function OnblurtxtPersonel(obj) {
            var RowIndex = obj.parentElement.parentElement.rowIndex;
            if (obj.value != "") {
                document.getElementById(MasterObj + "txtPersonCode").value = obj.value
                document.getElementById(MasterObj + "txtSubmit").value = "BlurPerson"
                document.getElementById(MasterObj + "BtnSubmitPerson").click()
            }
        }
        //=============================For BtnPerson... in Grid=======================
        function OnClickPersonBtn(obj) {
            var url = "/FrmPresentation/App_Pages/BaseInfo/Person/SelectPerson.aspx?Type=Check&SessionID=" + $get(MasterObj + "txtSessionID").value + "&OnLineUser=" + $get(MasterObj + "txtOnlineUser").value
            strOptions = "dialogHeight: 640px;dialogWidth: 800px;center: Yes;help: no;status: no"

            if (url != "") {
                var OSelectedMamber = ""
                OSelectedMamber = window.showModalDialog(url, "", strOptions)
                if (OSelectedMamber != undefined) {
                    var oXmlDoc = new ActiveXObject("Microsoft.XMLDOM");
                    oXmlDoc.async = "false";
                    oXmlDoc.loadXML(OSelectedMamber);
                    //alert(oXmlDoc.xml)
                    var oXmlNodes = oXmlDoc.documentElement.selectNodes("/Root/Tb");

                    var oGrid = obj.parentElement;
                    while (oGrid.tagName != "TABLE")
                        oGrid = oGrid.parentElement

                    var oRow = obj.parentElement;
                    while (oRow.tagName != "TR")
                        oRow = oRow.parentElement
                    var oIndex = oRow.rowIndex

                    if (oXmlNodes.length > 0) {
                        oGrid.rows(oIndex).cells(4).firstChild.value = oXmlNodes.item(0).selectSingleNode('PCode').text
                        oRow.setAttribute('PersonID', oXmlNodes.item(0).selectSingleNode('PID').text)
                        oGrid.rows(oIndex).cells(5).innerText = oXmlNodes.item(0).selectSingleNode('PName').text
                    }
                }
            }
            str += "<PersonCode>" + obj.parentElement.firstChild.value + "</PersonCode>"
        }
        //======================================================
        function CHECKISEMPTY() {
            var OGrdDepartmentPerson = document.getElementById(MasterObj + "GrdDepartmentPerson");
            var grdLen = OGrdDepartmentPerson.rows.length;
            if (document.getElementById(MasterObj + "txtDepartmentID").value != "" && document.getElementById(MasterObj + "txtDepartmentID").value != "0")
                for (var i = 1; i < grdLen; i++) {
                    if (OGrdDepartmentPerson.rows(i).cells(1).firstChild.value == "0") {
                        alert("لطقا نوع سمت را انتخاب کنيد")
                        OGrdDepartmentPerson.rows(i).cells(1).firstChild.setActive();
                        return false;
                    }
                    else
                        if (OGrdDepartmentPerson.rows(i).cells(3).firstChild.value == "") {
                            alert("لطفا نام سمت را وارد کنید")
                            OGrdDepartmentPerson.rows(i).cells(3).firstChild.setActive();
                            return false;
                        }
                        else
                            if (OGrdDepartmentPerson.rows(i).cells(4).firstChild.value == "") {
                                alert("لطقا شماره پرسنلي را وارد کنيد")
                                OGrdDepartmentPerson.rows(i).cells(4).firstChild.setActive();
                                return false;
                            }
                }
            else {
                alert("لطفا یک واحد را انتخاب کنيد")
                return false;
            }
            return true;
        }
//        //=========================================MakeXmlSave===============
//        function MakeXMLSave() {
//            var OGrdDepartmentPerson = document.getElementById(MasterObj + "GrdDepartmentPerson");
//            var grdLen = OGrdDepartmentPerson.rows.length;
//            for (var i = 1; i < grdLen; i++) {
//                Str += "<DepartmentPerson>"
//                if (OGrdDepartmentPerson.rows(i).cells(0).firstChild.checked)
//                    Str += "<Heade>1</Heade>"
//                else
//                    Str += "<Heade>0</Heade>"
//                Str += "<RoleType>" + OGrdDepartmentPerson.rows(i).cells(1).firstChild.value + "</RoleType>"
//                Str += "<DRoleID>" + OGrdDepartmentPerson.rows(i).cells(2).innerText + "</DRoleID>"
//                Str += "<RoleTitle>" + OGrdDepartmentPerson.rows(i).cells(3).firstChild.value + "</RoleTitle>"
//                Str += "<PersonCode>" + OGrdDepartmentPerson.rows(i).cells(4).firstChild.value + "</PersonCode>"
//                Str += "</DepartmentPerson>"
//            }
//            alert(Str)
//        }
        //======================================Open Page NewOrganChart==========================
        function OnClickBtnNewOrganChart() {
            var url = "NewOrganChart.aspx?DepartmentId=0" + "&SessionID=" + document.getElementById(MasterObj + "txtSessionID").value
            returnValue = window.showModalDialog(encodeURI(url), "", "dialogWidth=550px;dialogHeight=175px;status: no;");

            if (returnValue == 1) {
                document.getElementById(MasterObj + "txtSubmit").value = "treeRefresh"
                document.getElementById(MasterObj + "BtnSubmit").click()
            }
        }
        //=======================================Edit Node========================================
        function OnClickBtnEditDepartment() {
            var url = "NewOrganChart.aspx?DepartmentId=" + document.getElementById(MasterObj + "txtDepartmentID").value + "&SessionID=" + document.getElementById(MasterObj + "txtSessionID").value
            returnValue = window.showModalDialog(encodeURI(url), "", "dialogWidth=550px;dialogHeight=175px;status: no;");

            if (returnValue == 1) {
                document.getElementById(MasterObj + "txtSubmit").value = "treeRefresh"
                document.getElementById(MasterObj + "BtnSubmittree").click()
            }
        }
        //=====================================Open Page NewAndAssignRole=========================
        function OnClickBtnNewAndAssignRole() {
            if (document.getElementById(MasterObj + "txtDepartmentID").value == "" || document.getElementById(MasterObj + "txtDepartmentID").value == "0") {
                alert("یک واحد سازمانی را انتخاب نمایید")
                return;
            }
            //alert(document.getElementById(MasterObj + "txtDepartmentID").value)
            var url = "NewAndAssignRole.aspx?DepartmentId=" + document.getElementById(MasterObj + "txtDepartmentID").value + "&SessionID=" + document.getElementById(MasterObj + "txtSessionID").value
            returnValue = window.showModalDialog(encodeURI(url), "", "dialogWidth=600px;dialogHeight=175px;status: no;");
            if (returnValue == 1) {
                document.getElementById(MasterObj + "txtSubmit").value = "GridFilter"
                document.getElementById(MasterObj + "BtnSubmit").click()
            }
        }
        //==============================================Filter================================================
        function OnClickBtnFilter() {
            $get(MasterObj + "txtCmbCodePCode").value = $get(MasterObj + "cmbPerson_txtCode").value
            //$get(MasterObj + "TreeDepatment").Nodes[i]
            document.getElementById(MasterObj + "txtSubmit").value = "Filter"
            document.getElementById(MasterObj + "BtnSubmitFilter").click();
        }
        //=============================رنگی شدن سطر گرید با کلیک کردن روی سطر===============
        function OnClickGrd(SelectedRow) {
            if (window.event != null) {
                if (SelectedRow == null || SelectedRow.tagName == undefined) {
                    SelectedRow = window.event.srcElement.parentElement;
                    if (SelectedRow.tagName != "TR")
                        SelectedRow = SelectedRow.parentElement;
                }
                if (LastSelectedRow != null) {
                    LastSelectedRow.className = LastSelectedRowClass;
                }
                LastSelectedRowClass = SelectedRow.className;
                LastSelectedRow = SelectedRow;
                SelectedRow.className = "CssSelectedItemStyle";
            }
        }
        //=====================================================
        function OnClickBtnSave() {
            if (CHECKISEMPTY()) {
               // MakeXMLSave()
                //Str = "<Root>" + Str + "</Root>"
                //alert(Str)
               // document.getElementById(MasterObj + "txtXmlSave").value = Str;
               // Str = "";
                // document.getElementById(MasterObj + "txtSubmit").value = "Modify"
                //document.getElementById(MasterObj + "BtnSubmit").click()
            }
        }
        //========================Control Scroll When Node Selected==============================
                function ScrollToSelectedNode() {
                    if (document.getElementById(MasterObj + "txtDepartmentID").value != "0") {      
                        scrollTop = $('.NewClass').position().top;                        
                        scrollTop -= 400;                       
                       $('#DivTree').scrollTop(scrollTop);
                    }
               }
               //=============================For BtnPerson... in Grid=======================================================
               function OnClickPersonBtn(obj) {
                   var url = "/FrmPresentation/App_Pages/BaseInfo/Person/SelectPerson.aspx?Type=Check&SessionID=" + $get(MasterObj + "txtSessionID").value + "&OnLineUser=" + $get(MasterObj + "txtOnlineUser").value
                   strOptions = "dialogHeight: 640px;dialogWidth: 800px;center: Yes;help: no;status: no"

                   if (url != "") {
                       var OSelectedMamber = ""
                       OSelectedMamber = window.showModalDialog(url, "", strOptions)
                       if (OSelectedMamber != undefined) {
                           var oXmlDoc = new ActiveXObject("Microsoft.XMLDOM");
                           oXmlDoc.async = "false";
                           oXmlDoc.loadXML(OSelectedMamber);
                           //alert(oXmlDoc.xml)
                           var oXmlNodes = oXmlDoc.documentElement.selectNodes("/Root/Tb");

                           var oGrid = obj.parentElement;
                           while (oGrid.tagName != "TABLE")
                               oGrid = oGrid.parentElement

                           var oRow = obj.parentElement;
                           while (oRow.tagName != "TR")
                               oRow = oRow.parentElement
                           var oIndex = oRow.rowIndex

                           if (oXmlNodes.length > 0) {
                               oGrid.rows(oIndex).cells(4).firstChild.value = oXmlNodes.item(0).selectSingleNode('PCode').text
                               oRow.setAttribute('PersonID', oXmlNodes.item(0).selectSingleNode('PID').text)
                               oGrid.rows(oIndex).cells(5).innerText = oXmlNodes.item(0).selectSingleNode('PName').text
                           }
                       }
                   }
                   MakeXmlGrid(obj.parentElement.firstChild, "txtPersonel")
               }
               //===========================================پرسنلی textBox================================
//               function OnChangetxtPersonel(obj) {
//                   MakeXmlGrid(obj, "txtPersonel")
//               }
               //==================================== onchange کمبو نوع سمت===============================
               function OnChangeCmbRoleType(obj) {
                    MakeXmlGrid(obj, "CmbRoleType")
               }
               //===========================================نام سمت textBox================================
               function OnChangetxtRoleTitle(obj) {
                   MakeXmlGrid(obj, "txtRoleTitle")
               }
               //==========================نگهداشتن مقادیر گرید با تغییر نود=============================
               function MakeXmlGrid(obj, ControlName) {
                   var XmlNodeBase = "";
                   var OGrdDepartmentPerson = document.getElementById(MasterObj + "GrdDepartmentPerson");
                   var RowIndex = obj.parentElement.parentElement.rowIndex;
                  // var PersonID = OGrdDepartmentPerson.rows(RowIndex).getAttribute("PersonID")//Attribute row
                   var DepartmentID = document.getElementById(MasterObj + "txtDepartmentID").value
                   var strXML = "<Root>" + str + "</Root>";
                   var oXmlDocSave = new ActiveXObject("Microsoft.XMLDOM");
                   oXmlDocSave.loadXML(strXML);

                   //---------------------------------------------------------

                   if (document.getElementById(MasterObj + "txtXmlStr").value != "") {
                       var XmlBase = "<Root>" + document.getElementById(MasterObj + "txtXmlStr").value.toString() + "</Root>";
                       var oXmlDocBase = new ActiveXObject("Microsoft.XMLDOM");
                       oXmlDocBase.async = "false";
                       oXmlDocBase.loadXML(XmlBase);
                       XmlNodeBase = oXmlDocBase.documentElement.selectNodes("/Root/Tb");
                       //alert(oXmlDocBase.xml)
                   }
                   //---------------------------------------------------------

                   var XmlNodeTmp = "";
                   var XmlNodestr = "";
                   if ((strXML != "<Root></Root>") && (strXML != "<Root/>")) {
                       XmlNodeTmp = oXmlDocSave.documentElement.selectNodes("/Root/Tb[DepartmentID=" + DepartmentID + "and RowIndex=" + RowIndex + "]");
                       XmlNodestr = oXmlDocSave.documentElement.selectNodes("/Root/Tb[DepartmentID=" + DepartmentID + "]");
                   }
                       
                   //alert(RowIndex)
                   //alert(XmlNodeTmp.length)
                   if (XmlNodeTmp.length > 0) {
                       // alert("XML");
                      // for (var i = 0; i < XmlNodeTmp.length; i++) {
                       if (ControlName == "CheckBox") {
                           if (obj.checked == true) {
//                               for (var s = 0; s < XmlNodestr.length; s++)
//                                   XmlNodestr.item(s).selectSingleNode('Head').text = 0

                               XmlNodeTmp.item(0).selectSingleNode('Head').text = 1

//                               for (var j = 0; j < XmlNodeBase.length; j++) {
//                                   if (XmlNodeBase.item(j).selectSingleNode('DepartmentID').text == DepartmentID) {
//                                       XmlNodeBase.item(j).selectSingleNode('Head').text = 0;
//                                   }
//                               }
//                               
//                               if (oXmlDocBase != null) {
//                                   document.getElementById(MasterObj + "txtXmlStr").value = oXmlDocBase.xml;
//                                   document.getElementById(MasterObj + "txtXmlStr").value = document.getElementById(MasterObj + "txtXmlStr").value.replace("<Root>", "")
//                                   document.getElementById(MasterObj + "txtXmlStr").value = document.getElementById(MasterObj + "txtXmlStr").value.replace("</Root>", "")
//                               }
                           }
                           else
                               XmlNodeTmp.item(0).selectSingleNode('Head').text = 0
                           }
                           if (ControlName == "CmbRoleType")
                               XmlNodeTmp.item(0).selectSingleNode('RoleType').text = obj.value

                           else if (ControlName == "txtRoleTitle") 
                               XmlNodeTmp.item(0).selectSingleNode('RoleTitle').text = obj.value

                           else if (ControlName == "txtPersonel")
                               XmlNodeTmp.item(0).selectSingleNode('PersonCode').text = obj.value

                           str = oXmlDocSave.xml;
                           str = str.replace("<Root>", "")
                           str = str.replace("</Root>", "")
                      //  }
                  }
                   else {
                       str += "<Tb>";
                       str += "<DepartmentID>" + DepartmentID + "</DepartmentID>"
                      // str += "<PersonID>" + PersonID + "</PersonID>"
                       str += "<RowIndex>" + RowIndex + "</RowIndex>"//For Attribute Row
                       if (OGrdDepartmentPerson.rows(RowIndex).cells(0).firstChild.checked == true) {
//                           for (var s1 = 0; s1 < XmlNodestr.length; s++)
//                               XmlNodestr.item(s1).selectSingleNode('Head').text = 0
                           str += "<Head>1</Head>"
//                           for (var j = 0; j < XmlNodeBase.length; j++) {
//                               if (XmlNodeBase.item(j).selectSingleNode('DepartmentID').text == DepartmentID)
//                                   XmlNodeBase.item(j).selectSingleNode('Head').text = 0;
//                           }
//                           if (oXmlDocBase != null) {
//                               document.getElementById(MasterObj + "txtXmlStr").value = oXmlDocBase.xml;
//                               document.getElementById(MasterObj + "txtXmlStr").value = document.getElementById(MasterObj + "txtXmlStr").value.replace("<Root>", "")
//                               document.getElementById(MasterObj + "txtXmlStr").value = document.getElementById(MasterObj + "txtXmlStr").value.replace("</Root>", "")
//                           }
                       }
                       else
                           str += "<Head>0</Head>"
                       str += "<RoleType>" + OGrdDepartmentPerson.rows(RowIndex).cells(1).firstChild.value + "</RoleType>"
                       str += "<DRoleID>" + OGrdDepartmentPerson.rows(RowIndex).cells(2).innerText + "</DRoleID>"
                       str += "<RoleTitle>" + OGrdDepartmentPerson.rows(RowIndex).cells(3).firstChild.value + "</RoleTitle>"
                       str += "<PersonCode>" + OGrdDepartmentPerson.rows(RowIndex).cells(4).firstChild.value + "</PersonCode>"

                       str += "</Tb>";
                   }
                   //alert(str)
               }
               //==================================Load Xml When going to another Node===================
               function LoadXMLGrid() {
                   var OGrdDepartmentPerson = document.getElementById(MasterObj + "GrdDepartmentPerson");
                   //var PersonID = OGrdDepartmentPerson.rows(RowIndex).getAttribute("PersonID")
                   //var GrdLenP=OGrdDepartmentPerson.rows.length
                   document.getElementById(MasterObj + "txtXmlStr").value += str
                  // alert(document.getElementById(MasterObj + "txtXmlStr").value)
                   str=""
                   var XMLGrid = document.getElementById(MasterObj + "txtXmlStr").value
                   var lengthEmptyRow = OGrdDepartmentPerson.rows.length
                   //alert(XMLGrid)
                   if (XMLGrid != "") {
                       XMLGrid = "<Root>" + XMLGrid + "</Root>"
                       var oXmlDoc = new ActiveXObject("Microsoft.XMLDOM");
                       oXmlDoc.async = "false";
                       oXmlDoc.loadXML(XMLGrid);
                       if ((XMLGrid != "<Root></Root>") && (XMLGrid != "<Root/>"))
                           var XmlNode = oXmlDoc.documentElement.selectNodes("/Root/Tb[DepartmentID=" + document.getElementById(MasterObj + "txtDepartmentID").value + "]")
                       
                       //var Flag = OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).getAttribute("Flag")//For seprate Rows Gets From SP and NewRow
                       for (var i = 0; i < XmlNode.length; i++) {
                           
                       //alert(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString()))
                          // alert(OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).getAttribute("Flag"))
                           if (OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).getAttribute("Flag") == 1) {
                               if (XmlNode.item(i).selectSingleNode('Head').text.toString() == "1")
                                   OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).cells(0).firstChild.checked = true
                               else OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).cells(0).firstChild.checked = false

                               OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).cells(1).firstChild.value = XmlNode.item(i).selectSingleNode('RoleType').text.toString()
                               //OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).cells(2).firstChild.value = XmlNode.item(i).selectSingleNode('DRoleID').text.toString()
                               OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).cells(3).firstChild.value = XmlNode.item(i).selectSingleNode('RoleTitle').text.toString()
                               OGrdDepartmentPerson.rows(parseInt(XmlNode.item(i).selectSingleNode('RowIndex').text.toString())).cells(4).firstChild.value = XmlNode.item(i).selectSingleNode('PersonCode').text.toString()
                           }
                           else {
                               addrow(XmlNode.item(i).selectSingleNode('Head').text.toString(),
                                  XmlNode.item(i).selectSingleNode('RoleType').text.toString(),
                                  XmlNode.item(i).selectSingleNode('DRoleID').text.toString(),
                                  XmlNode.item(i).selectSingleNode('RoleTitle').text.toString(),
                                  XmlNode.item(i).selectSingleNode('PersonCode').text.toString(),
                                  XmlNode.item(i).selectSingleNode('RowIndex').text.toString()
                                  )
                           }
                       }
                       //alert(lengthEmptyRow)
                       //alert(OGrdDepartmentPerson.rows.length)
                       if (OGrdDepartmentPerson.rows.length > 2 && XmlNode.length > 0) 
                           OGrdDepartmentPerson.deleteRow(lengthEmptyRow - 1)
                   }
               }
               //================================Add Row for Load Grid when going to another Node============================
               function addrow(Head, RoleType, DRoleID, RoleTitle, PersonCode, RowIndex) {
                   
                   var OGrdDepartmentPerson = document.getElementById(MasterObj + "GrdDepartmentPerson");
                   //var Chk = OGrdDepartmentPerson.rows(1).cells(0).innerHTML
                  
                  
                   var oRow = OGrdDepartmentPerson.insertRow();
                   OGrdDepartmentPerson.rows(parseInt(RowIndex)).setAttribute('Flag', 0);//set Flag 0 For loading again
//                   alert(OGrdDepartmentPerson.rows(parseInt(RowIndex)).getAttribute("Flag"))
                   oRow.className = "CssItemStyle";
                   oRow.setAttribute('RowIndex', RowIndex);
                   oRow.attachEvent('onclick', OnClickGrd)

                   var oCell0 = oRow.insertCell();
                   oCell0.innerHTML = OGrdDepartmentPerson.rows(1).cells(0).innerHTML
                   if (Head == "1")
                       oCell0.firstChild.checked = true;
                   else oCell0.firstChild.checked = false;

                   var oCelll = oRow.insertCell();
                   oCelll.innerHTML = OGrdDepartmentPerson.rows(1).cells(1).innerHTML
                   oCelll.firstChild.value = RoleType

                   var oCell2 = oRow.insertCell();
                   oCell2.innerHTML = OGrdDepartmentPerson.rows(1).cells(2).innerHTML
                   oCell2.innerText = DRoleID

                   var oCell3 = oRow.insertCell();
                   oCell3.innerHTML = OGrdDepartmentPerson.rows(1).cells(3).innerHTML
                   oCell3.firstChild.value = RoleTitle

                   var oCell4 = oRow.insertCell();
                   oCell4.innerHTML = OGrdDepartmentPerson.rows(1).cells(4).innerHTML
                   oCell4.firstChild.value = PersonCode

                   var oCell5 = oRow.insertCell();
                   oCell5.innerHTML = OGrdDepartmentPerson.rows(1).cells(5).innerHTML
                   oCell5.innerText = ""

                   var oCell6 = oRow.insertCell();
                   oCell6.innerHTML = OGrdDepartmentPerson.rows(1).cells(6).innerHTML
               }
               //=======================================حذف پرسنل از سمت=======================
               function OnClickBtnDelPersonel() {
                   if (LastSelectedRow != null) {
                       var Msg = "آیا برای حذف مطمئن هستید ؟"
                       if (confirm(Msg) == true) {
                           document.getElementById(MasterObj + "txtDeleteFlag").value ="4"
                           document.getElementById(MasterObj + "txtSubmit").value = "Delete"
                           document.getElementById(MasterObj + "BtnSubmit").click()
                       }
                   }
                   else
                       alert("به منظور حذف یک سطر را انتخاب کنید")
               }
               //========================================حذف سمت================================
               function OnClickBtnDellRoll() {
                   //if (document.getElementById(MasterObj + "txtDepartmentID").value != "" && document.getElementById(MasterObj + "txtDepartmentID").value != "0") {
                       if (LastSelectedRow != null) {
                           var Msg = "آیا برای حذف مطمئن هستید ؟"
                           if (confirm(Msg) == true) {
                               document.getElementById(MasterObj + "txtDeleteFlag").value = "5"
                               document.getElementById(MasterObj + "txtSubmit").value = "Delete"
                               document.getElementById(MasterObj + "BtnSubmit").click()
                           }
                       }
                       else
                           alert("به منظور حذف یک سطر را انتخاب کنید")
                   //}
                   //else  alert("به منظور حذف یک واحد را انتخاب کنید")
               }
               //=======================================حذف واحد================================
               function OnClickBtnDelDepartment() {
                   if (document.getElementById(MasterObj + "txtDepartmentID").value != "" && document.getElementById(MasterObj + "txtDepartmentID").value != "0") {
                       var Msg = "آیا برای حذف مطمئن هستید ؟"
                       if (confirm(Msg) == true) {
                           document.getElementById(MasterObj + "txtDeleteFlag").value = "0"
                           document.getElementById(MasterObj + "txtSubmit").value = "Delete"
                           document.getElementById(MasterObj + "BtnSubmit").click()
                       }
                   }
                   else
                       alert("به منظور حذف یک واحد را انتخاب کنید")
               }
    </script>
</asp:Content>
