USE master;
GO
ALTER DATABASE [Framework] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO


ALTER DATABASE Framework COLLATE  SQL_Latin1_General_CP1_CI_AS


use master
GO
ALTER DATABASE Framework
SET MULTI_USER
GO