<%
	Dim  RightBackground as string
	Dim  LeftBackground as string
	
	LeftBackground = OnlineUser.CommonLib.BaseURL & "IMAGES/backgrounds/bI0.jpg ""   bottomMargin='0' leftMargin='0' topMargin='0' rightMargin='0' align=""center"" class=""VertGradient2"
	RightBackground= OnlineUser.CommonLib.BaseURL & "images/backgrounds/ALT.BMP ""   style="" FILTER:progid:DXImageTransform.Microsoft.Gradient(GradientType=1, StartColorStr='#00000000', EndColorStr='#40000020')"
%>
